# -*- coding: utf-8 -*-
"""Question-03-Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110d58UT3q-BSAqB-3FQ_s4AWziQs9Djv
"""

!pip install pyinputplus

import pyinputplus as pyp
import numpy as npy
import pandas as pnd
import matplotlib.pyplot as plt


#####################################################################

class EmployeeLogin:
  def __init__(self,Name,Department,EmplyNum):
   self.Name = Name
   self.Department = Department
   self.EmplyNum = EmplyNum


Name = pyp.inputStr("Please Enter your Name")
Department = pyp.inputStr("Please Enter your Department")
EmplyNum = pyp.inputStr("Please Enter EmplyNum")

info = EmployeeLogin(Name,Department,EmplyNum)
print("The logged in Employee Name is",info.Name)
print("The Department of the Employee",Name,"is",info.Department)
print("The Employee Id of logged in Employee",Name,"is",info.EmplyNum)


#######################################################################
print("Please Enter  Kilometers Travelled (Km) per Year")
Kilom = []
Year = ['2018','2019','2020','2021','2022']

for i in Year:
    Km_trvld= pyp.inputFloat(i)
    Kilom.append(Km_trvld)

print("The Following are the km travelled per Year " , Kilom)
#######################################################################
print("Please Enter Fuel Efficiency per Year")
Fuel_Effc = []
Year = ['2018','2019','2020','2021','2022']

for i in Year:
    Effc= pyp.inputFloat(i)
    Fuel_Effc.append(Effc)

print("The Followwing is the efficiency per month " , "is",Fuel_Effc)
#####################################################################
z=1
mulp_2 = z/npy.array(Fuel_Effc)
print(mulp_2)

mulp_3 = Kilom*mulp_2
print(mulp_3)

#####################################################################
total_Carbon = 2.31*mulp_3

total_Carbon_1 = npy.around(total_Carbon,2)

####################################################################
Year = ['2018','2019','2020','2021','2022']

table = {'Year':['2018','2019','2020','2021','2022'],
         'Kilometre Travelled(KM)':Kilom,
         'Fuel Efficiency':mulp_2,
         'Total Carbon (KgCO2)':total_Carbon_1
         }
df=pnd.DataFrame(table)
print(df)

##################################################################
# Year VS Kilometre Travelled


plt.figure("Year - Kilomtre Travelled",figsize=[12,4])
plt.title("Year - Kilometre Travelled (KM)")
plt.xlabel('Month')
plt.ylabel(' Kilometre Travelled (KM)')
plt.plot(Year,Kilom,color='blue')
plt.show()

#####################################################################
# Year VS Carbon Generated

plt.figure("Year - Carbon Generated",figsize=[12,4])
plt.title("Year - Carbon Generated (KGC02)")
plt.xlabel('Year')
plt.ylabel(' Carbon Generated (KGC02)')
plt.plot(Year,total_Carbon_1,color='blue')
plt.show()




###################################################################
df.to_excel("Question03.xlsx")