# -*- coding: utf-8 -*-
"""Question-02-Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SIP-O3_HIkJuxjoDM5kWHxlyrD7FGQtd
"""

!pip install pyinputplus

import pyinputplus as pyp
import numpy as npy
import pandas as pnd
import matplotlib.pyplot as plt



############################################################################

class EmployeeLogin:
  def __init__(self,Name,Department,EmplyNum):
   self.Name = Name
   self.Department = Department
   self.EmplyNum = EmplyNum


Name = pyp.inputStr("Please Enter your Name")
Department = pyp.inputStr("Please Enter your Department")
EmplyNum = pyp.inputStr("Please Enter EmplyNum")

info = EmployeeLogin(Name,Department,EmplyNum)
print("The logged in Employee Name is",info.Name)
print("The Department of the Employee",Name,"is",info.Department)
print("The Employee Id of logged in Employee",Name,"is",info.EmplyNum)


#############################################################################
print("Please Enter Monthly Waste Generated (Kg)")
Waste_Kg = []
months = ['January','Febuary','March','April','May','June','July','August','September','October','November','December']

for i in months:
    waste= pyp.inputFloat(i)
    Waste_Kg.append(waste)

print("The Following are the Waste Generated in Kg by Month " ,Waste_Kg)

#############################################################################
print("Please Enter Monthly Recycling Compost (KG)")
Compost_Kg = []
months = ['January','Febuary','March','April','May','June','July','August','September','October','November','December']

for i in months:
    compost= pyp.inputFloat(i)
    Compost_Kg.append(compost)

print("The Following are the Compost Generated in Kg by Month " ,Compost_Kg)

#############################################################
# The Following Code Finds the Percentage composted by dividing waste with Compost

Percentage_Recycled = npy.array(Compost_Kg)/npy.array(Waste_Kg)
print("The Following are the Percentage of Compost",npy.around(Percentage_Recycled,2))

#############
#Finding The total Carbon Generated

carbon_gen_waste = 0.57 - npy.array(Percentage_Recycled)
print(carbon_gen_waste)

total_Carbon_Gen =npy.array(Waste_Kg) * 12 * npy.array(carbon_gen_waste)
print(total_Carbon_Gen)

######################################################################################
table = {'Month':['Jan','Feb','Mrch','Aprl','May','Jun','Jul','Aug','Sept','Oct','Nov','Dec'],
         'Waste Generated(KG)': Waste_Kg,
         'Carbon Generated (KgC02)':total_Carbon_Gen,
         #'Fuel Carbon(KgCO2)':Fuel_Carbon_1,
         #'Total(KgCO2)':Total_Carbon
         }
df=pnd.DataFrame(table)
print(df)

#######################################################################################

# Month VS Waste Generated

plt.figure("Month - Waste Generated",figsize=[12,4])
plt.title("Month - Waste Generated (KG)")
plt.xlabel('Month')
plt.ylabel(' Waste Generated (KG)')
plt.plot(months,Waste_Kg,color='blue')
plt.show()
###################################################################

plt.figure("Month - Total Carbon (KGC02)",figsize=[12,4])
plt.title("Month - Total Carbon (KGC02)")
plt.xlabel('Month')
plt.ylabel(' Total Carbon (KGC02)')
plt.plot(months,total_Carbon_Gen,color='blue')
plt.show()


###################################################################
df.to_excel("Question02.xlsx")      #Transfers Data onto Excel